name: Chisel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up SKDMAN
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install sbt
        which sbt
    - name: Clone manticore chisel project
      uses: actions/checkout@v2
      with:
        repository: epfl-vlsc/manticore
        token : ${{ secrets.MANTICORE_CLONE_ACCESS }}
        path  : manticore-machine
    - name: "publish manticore locally"
      run: |
        cd manticore-machine
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sbt "publishLocal"
        cd ..
    - name: "Install verilator"
      run: |
        sudo apt install verilator
    - name: Run chisel based tests
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sbt 'testOnly -- -m manticore.compiler.integration.chisel'


